### ISSUE TITLE
Accept custom styles for ol-kit components

### ISSUE THREAD

**Issue by PizzaBrandon** [Bayer-Group/ol-kit#93]

**Comment by ntatko** [comment]
Thinking about using MUI themes, which would be added to the provider context.

```JSX
<Map
  map={this.myMap}
  theme={createMuiTheme({
    palette: {
      primary: '#0000FF',
    },
  })}
/>
```
If you wanted a component to have a different theme, this would be simple:
```JSX
<Map
  theme={createMuiTheme({
    palette: {
      primary: '#0000FF'
    },
  })}
>
  <Child
    theme={createMuiTheme({
      palette: {
        primary: '#00FF00'
      }
    })}
</Map>
```

The context that we already use would make this pretty simple.

I'm open to other ideas. Thoughts?

**Comment by ntatko** [comment]
<img width="411" alt="Screen Shot 2020-06-30 at 03 34 13" src="https://user-images.githubusercontent.com/37306038/86103699-b4cbee80-ba82-11ea-94fe-0028a49e302b.png">
Prototype of the layer panel with the default dark theme.
```JSX
<Map onMapInit={this.onMapInit} fullScreen
  theme={
    createMuiTheme({
      palette: {
        type: 'dark'
      }
    })
  }
>
```
Still a WIP, but going smoother than I was thinking it would.

**Comment by ntatko** [comment]
This is dark mode for the controls and Layer panel. I changed the color, because the secondary color for material-ui is obnoxious.
<img width="415" alt="Screen Shot 2020-07-01 at 00 06 57" src="https://user-images.githubusercontent.com/37306038/86205198-e5696200-bb2e-11ea-8b5b-c9e7b56212bd.png">
<img width="83" alt="Screen Shot 2020-07-01 at 00 06 39" src="https://user-images.githubusercontent.com/37306038/86205199-e69a8f00-bb2e-11ea-84ff-cbece9d56c1e.png">
```JSX
<Map onMapInit={this.onMapInit} fullScreen
  theme={
    createMuiTheme({
      palette: {
        type: 'dark',
        secondary: {
          main: '#90caf9'
        }
      }
    })
  }
>
```

And then, with a one string change, let there be light:

<img width="410" alt="Screen Shot 2020-07-01 at 00 10 35" src="https://user-images.githubusercontent.com/37306038/86205431-72acb680-bb2f-11ea-8378-72013e941960.png">
<img width="65" alt="Screen Shot 2020-07-01 at 00 10 46" src="https://user-images.githubusercontent.com/37306038/86205428-717b8980-bb2f-11ea-8fbc-0d9aaeb6ed8f.png">

```JSX
<Map onMapInit={this.onMapInit} fullScreen
  theme={
    createMuiTheme({
      palette: {
        type: 'light',
        secondary: {
          main: '#90caf9'
        }
      }
    })
  }
>
```

**Comment by ntatko** [comment]
Popup's done.
<img width="271" alt="Screen Shot 2020-07-01 at 01 42 31" src="https://user-images.githubusercontent.com/37306038/86211565-35025a80-bb3c-11ea-94b5-2a0a7d784f13.png">

**Comment by ntatko** [comment]
Think I'm going to get `TimeSlider` for free, as it's pretty much material anyway.

**Comment by ntatko** [comment]
https://github.com/MonsantoCo/ol-kit/issues/206#issue-715841560 Good idea.

**Comment by akuma1** [comment]
We are deprecating ol-kit. 
You may consider these alternatives:
- Use openlayers directly as recent versions of openlayers provides quite a bit of functionality out of box.  
- Additionally , you can take a look at these [openlayers libraries](https://openlayers.org/3rd-party/).
